services:
  app:
    build: ./
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
